version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwtcrud
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - jwt-crud-api_mongo-data:/data/db
    ports:
      - "27017:27017"  

volumes:
  jwt-crud-api_mongo-data:

