name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests (non-blocking)
        run: |
          echo "Running tests..."
          npm test || echo "No tests or test failed, continuing..."

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: docker buildx build --push -t ${{ secrets.DOCKER_USERNAME }}/jwt-crud-api:latest .

      - name: Clean up Docker containers
        run: |
          docker container prune -f
          docker image prune -f
