name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests (non-blocking)
        run: |
          echo "Running tests..."
          npm test || echo "No tests or test failed, continuing..."

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Debug Docker username
        run: echo "Docker username is: ${{ secrets.DOCKER_USERNAME }}"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jwt-crud-api:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jwt-crud-api:latest

      - name: Clean up Docker containers
        run: |
          docker container prune -f
          docker image prune -f
