name: CI/CD Pipeline

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version you want to use

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests (this is optional for now since you don't have tests)
    - name: Run tests
      run: |
        if [ -f package.json ]; then
          echo "Running tests..."
          npm test || exit 0  # If no tests exist, it won't fail the pipeline
        else
          echo "No tests found"
        fi

    # Build Docker image
    - name: Build Docker image
      run: docker build -t jwt-crud-api .

    # Run the Docker container (locally in GitHub Actions)
    - name: Run Docker container
      run: docker run -d -p 3000:3000 jwt-crud-api

    # Docker Hub login using secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Reference the secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Reference the secret for Docker Hub password

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push jwt-crud-api:latest  # Push the Docker image with the "latest" tag

    # Optional: Clean up Docker containers
    - name: Clean up Docker containers
      run: docker rm -f $(docker ps -aq)

