name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    
    - name: Build Docker image
      run: |
        docker build -t jwt-crud-api-app .
    
    - name: Run Docker container locally
      run: |
        docker run -d -p 3000:3000 jwt-crud-api-app
    
    - name: Verify Docker container is running
      run: |
        curl --silent --fail http://localhost:3000 || exit 1

    - name: Clean up
      run: |
        docker stop $(docker ps -q)
        docker rm $(docker ps -a -q)

